### ISSUE TITLE
Break in slow tests

### ISSUE THREAD

**Issue by gpsaggese** [causify-ai/helpers#553]
GP Saggese

Friday at 5:43 PM
[@Sonya Nikiforova](https://causify.slack.com/team/U082BFT5S66)
 same glitch-y test linters/test/test_amp_dev_scripts.py::Test_linter_py1::test_linter_md1

That's a completely different error than before. Now it's failing because of some problem using the dockerized prettier. I'm guessing, it's because in [this PR](https://github.com/causify-ai/helpers/pull/544) the default behavior of dev_scripts_helpers/documentation/lint_notes.py was changed from using prettier installed on the host to using the dockerized executable.  To be more precise, the option to use prettier installed on the host was removed completely. BTW the PR was merged even though the slow tests were failing in it. Is there a way to completely block merging a PR if it breaks fast/slow tests? This is not the first time the build breaks because a PR was merged without accounting for the fact that it doesn't pass the fast/slow test checks.

FYI @dremdem @sonniki

**Comment by dremdem** [comment]
> BTW the PR was merged even though the slow tests were failing in it. Is there a way to completely block merging a PR if it breaks fast/slow tests?

I think there are some settings already in place:
<img width="1408" alt="Image" src="https://github.com/user-attachments/assets/c043648b-b014-4bf9-9241-8cfb5dc0c6b8" />

It's possible they are already configured, but there might be a `bypass` with your username: 
<img width="1836" alt="Image" src="https://github.com/user-attachments/assets/eaa6bba6-8615-451a-8e18-2017cc4fe70e" />

**Comment by heanhsok** [comment]
> That's a completely different error than before. Now it's failing because of some problem using the dockerized prettier. I'm guessing, it's because in https://github.com/causify-ai/helpers/pull/544 the default behavior of dev_scripts_helpers/documentation/lint_notes.py was changed from using prettier installed on the host to using the dockerized executable. To be more precise, the option to use prettier installed on the host was removed completely.

This PR https://github.com/causify-ai/helpers/pull/558 should fix the slow test

1) The issue is related to the mounting path of the source dir in the dockerized executables. It looks like we can't use the sibling container approach here. The children container approach should work. We can use the `hserver.use_docker_sibling_containers()` to check if sibling container is supported.
2) I have enabled this dockerized executables tests on our CI as it doesn't take too long to run. LMK if we should disable it like the others.

FYI @gpsaggese @sonniki 

```
user_1042@f8811eb590fd:/app$ python3 ./linters/amp_lint_md.py README.md
13:54:58 - INFO  hdbg.py init_logger:1018                               > cmd='./linters/amp_lint_md.py README.md'
13:55:01 - ERROR hsystem.py _system:252
################################################################################
cmd='($(find -wholename '*dev_scripts_helpers/documentation/lint_notes.py') -i README.md --in_place) 2>&1' failed with rc='1'
################################################################################
Output of the failing command is:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
13:55:01 - INFO  hdbg.py init_logger:1018                               > cmd='./dev_scripts_helpers/documentation/lint_notes.py -i README.md --in_place'
13:55:01 - ERROR hsystem.py _system:252
################################################################################
cmd='(docker run --rm --user $(id -u):$(id -g) -e AM_CONTAINER_VERSION -e CSFY_AWS_ACCESS_KEY_ID -e CSFY_AWS_DEFAULT_REGION -e CSFY_AWS_PROFILE -e CSFY_AWS_S3_BUCKET -e CSFY_AWS_SECRET_ACCESS_KEY -e CSFY_AWS_SESSION_TOKEN -e CSFY_CI -e CSFY_ECR_BASE_PATH -e CSFY_ENABLE_DIND -e CSFY_FORCE_TEST_FAIL -e CSFY_GIT_ROOT_PATH -e CSFY_HELPERS_ROOT_PATH -e CSFY_HOST_GIT_ROOT_PATH -e CSFY_HOST_NAME -e CSFY_HOST_OS_NAME -e CSFY_HOST_USER_NAME -e CSFY_HOST_VERSION -e CSFY_REPO_CONFIG_CHECK -e CSFY_REPO_CONFIG_PATH -e CSFY_TELEGRAM_TOKEN -e CSFY_USE_HELPERS_AS_NESTED_MODULE -e OPENAI_API_KEY  --entrypoint '' --workdir /app --mount type=bind,source=/data/heanhs/src/helpers2,target=/app tmp.prettier.x86_64.0ea6c25d bash -c "/usr/local/bin/prettier --parser markdown --prose-wrap always --tab-width 2 --print-width 80 --write /app/tmp.lint_notes.prettier.txt") 2>&1' failed with rc='125'
################################################################################
Output of the failing command is:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /data/heanhs/src/helpers2

Run 'docker run --help' for more information

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Traceback (most recent call last):
  File "/app/./dev_scripts_helpers/documentation/lint_notes.py", line 409, in <module>
    _main(args_)
  File "/app/./dev_scripts_helpers/documentation/lint_notes.py", line 393, in _main
    txt = _process(
          ^^^^^^^^^
  File "/app/./dev_scripts_helpers/documentation/lint_notes.py", line 311, in _process
    txt = prettier_on_str(txt)
          ^^^^^^^^^^^^^^^^^^^^
  File "/app/./dev_scripts_helpers/documentation/lint_notes.py", line 143, in prettier_on_str
    prettier(tmp_file_name, tmp_file_name, *args, **kwargs)
  File "/app/./dev_scripts_helpers/documentation/lint_notes.py", line 119, in prettier
    hdocker.run_dockerized_prettier(
  File "/app/helpers/hdocker.py", line 670, in run_dockerized_prettier
    hsystem.system(docker_cmd)
  File "/app/helpers/hsystem.py", line 309, in system
    rc, _ = _system(
            ^^^^^^^^
  File "/app/helpers/hsystem.py", line 263, in _system
    raise RuntimeError(msg)
RuntimeError:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
_system failed: cmd='(docker run --rm --user $(id -u):$(id -g) -e AM_CONTAINER_VERSION -e CSFY_AWS_ACCESS_KEY_ID -e CSFY_AWS_DEFAULT_REGION -e CSFY_AWS_PROFILE -e CSFY_AWS_S3_BUCKET -e CSFY_AWS_SECRET_ACCESS_KEY -e CSFY_AWS_SESSION_TOKEN -e CSFY_CI -e CSFY_ECR_BASE_PATH -e CSFY_ENABLE_DIND -e CSFY_FORCE_TEST_FAIL -e CSFY_GIT_ROOT_PATH -e CSFY_HELPERS_ROOT_PATH -e CSFY_HOST_GIT_ROOT_PATH -e CSFY_HOST_NAME -e CSFY_HOST_OS_NAME -e CSFY_HOST_USER_NAME -e CSFY_HOST_VERSION -e CSFY_REPO_CONFIG_CHECK -e CSFY_REPO_CONFIG_PATH -e CSFY_TELEGRAM_TOKEN -e CSFY_USE_HELPERS_AS_NESTED_MODULE -e OPENAI_API_KEY  --entrypoint '' --workdir /app --mount type=bind,source=/data/heanhs/src/helpers2,target=/app tmp.prettier.x86_64.0ea6c25d bash -c "/usr/local/bin/prettier --parser markdown --prose-wrap always --tab-width 2 --print-width 80 --write /app/tmp.lint_notes.prettier.txt") 2>&1'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
truncated output=
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /data/heanhs/src/helpers2

Run 'docker run --help' for more information


<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Traceback (most recent call last):
  File "/app/./linters/amp_lint_md.py", line 114, in <module>
    _main(_parse())
  File "/app/./linters/amp_lint_md.py", line 110, in _main
    action.run(args.files)
  File "/app/linters/action.py", line 90, in run
    output = self.execute(file_name, pedantic=0)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/linters/action.py", line 73, in execute
    output = self._execute(file_name, pedantic)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/./linters/amp_lint_md.py", line 71, in _execute
    _, output = liutils.tee(cmd_as_str, self._executable, abort_on_error=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/linters/utils.py", line 109, in tee
    rc, output = hsystem.system_to_string(cmd, abort_on_error=abort_on_error)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/helpers/hsystem.py", line 350, in system_to_string
    rc, output = _system(
                 ^^^^^^^^
  File "/app/helpers/hsystem.py", line 263, in _system
    raise RuntimeError(msg)
RuntimeError:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
_system failed: cmd='($(find -wholename '*dev_scripts_helpers/documentation/lint_notes.py') -i README.md --in_place) 2>&1'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
truncated output=
13:55:01 - INFO  hdbg.py init_logger:1018                               > cmd='./dev_scripts_helpers/documentation/lint_notes.py -i README.md --in_place'
13:55:01 - ERROR hsystem.py _system:252
################################################################################
cmd='(docker run --rm --user $(id -u):$(id -g) -e AM_CONTAINER_VERSION -e CSFY_AWS_ACCESS_KEY_ID -e CSFY_AWS_DEFAULT_REGION -e CSFY_AWS_PROFILE -e CSFY_AWS_S3_BUCKET -e CSFY_AWS_SECRET_ACCESS_KEY -e CSFY_AWS_SESSION_TOKEN -e CSFY_CI -e CSFY_ECR_BASE_PATH -e CSFY_ENABLE_DIND -e CSFY_FORCE_TEST_FAIL -e CSFY_GIT_ROOT_PATH -e CSFY_HELPERS_ROOT_PATH -e CSFY_HOST_GIT_ROOT_PATH -e CSFY_HOST_NAME -e CSFY_HOST_OS_NAME -e CSFY_HOST_USER_NAME -e CSFY_HOST_VERSION -e CSFY_REPO_CONFIG_CHECK -e CSFY_REPO_CONFIG_PATH -e CSFY_TELEGRAM_TOKEN -e CSFY_USE_HELPERS_AS_NESTED_MODULE -e OPENAI_API_KEY  --entrypoint '' --workdir /app --mount type=bind,source=/data/heanhs/src/helpers2,target=/app tmp.prettier.x86_64.0ea6c25d bash -c "/usr/local/bin/prettier --parser markdown --prose-wrap always --tab-width 2 --print-width 80 --write /app/tmp.lint_notes.prettier.txt") 2>&1' failed with rc='125'
################################################################################
Output of the failing command is:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /data/heanhs/src/helpers2

Run 'docker run --help' for more information

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Traceback (most recent call last):
  File "/app/./dev_scripts_helpers/documentation/lint_notes.py", line 409, in <module>
    _main(args_)
  File "/app/./dev_scripts_helpers/documentation/lint_notes.py", line 393, in _main
    txt = _process(
          ^^^^^^^^^
  File "/app/./dev_scripts_helpers/documentation/lint_notes.py", line 311, in _process
    txt = prettier_on_str(txt)
          ^^^^^^^^^^^^^^^^^^^^
  File "/app/./dev_scripts_helpers/documentation/lint_notes.py", line 143, in prettier_on_str
    prettier(tmp_file_name, tmp_file_name, *args, **kwargs)
  File "/app/./dev_scripts_helpers/documentation/lint_notes.py", line 119, in prettier
    hdocker.run_dockerized_prettier(
  File "/app/helpers/hdocker.py", line 670, in run_dockerized_prettier
    hsystem.system(docker_cmd)
  File "/app/helpers/hsystem.py", line 309, in system
    rc, _ = _system(
            ^^^^^^^^
```

**Comment by sonniki** [comment]
The fix from @heanhsok is good, thank you for jumping on to fix the build.
As a side note, I don't understand why we had to disable the option in `dev_scripts_helpers/documentation/lint_notes.py` to run `prettier` on a host system directly, given that `prettier` is already installed in the `helpers` image anyway

**Comment by gpsaggese** [comment]
Good job @heanhsok 

1) The goal is to push everything through dockerized executables and support sibling and dind indifferently. I am close to being able to do that
2) I'm ok with restoring the stuff removed (too early).

**Comment by heanhsok** [comment]
> @heanhsok do you know if your fix would also fix this?

Yes it should as it looks like the same error.

**Comment by gpsaggese** [comment]
1) I'm fixing this by partial revert, since the PR is not ready yet.

2) @sonniki I still get this glitching behavior. One line in the golden shows up at different points on different computers. I think it's a race in the OS itself, based on how stderr and stdout are piped together. My suggestion is to filter out that line and / or change the test.

<img width="1992" alt="Image" src="https://github.com/user-attachments/assets/3bb1496b-867f-43cf-91e4-a0504522c845" />

**Comment by sonniki** [comment]
> @sonniki I still get this glitching behavior. One line in the golden shows up at different points on different computers. I think it's a race in the OS itself, based on how stderr and stdout are piped together. My suggestion is to filter out that line and / or change the test.

Filed #568. Will outsource to an intern to fix.

**Comment by sonniki** [comment]
Linter GH Action was still [throwing an error](https://github.com/causify-ai/helpers/actions/runs/14473917294/job/40594697250?pr=564) because of an invalid tmp file path for running `prettier`. I did a quick fix in #570 to unblock (reverting to the way it was before), LMK if there is a need to follow up
